app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$snapshot()
app$setInputs(sigma2 = 4)
app$snapshot()
app$setInputs(display = c("Components (pdf)", "Data (rug)"))
app$setInputs(display = "Components (pdf)")
app$setInputs(display = character(0))
app$setInputs(display = "Components (pdf)")
app$setInputs(select = "Gaussian Mixture Model")
app$setInputs(histo = TRUE)
app$snapshot()
app$setInputs(select = "K-means Clustering")
app$setInputs(p2 = 0.75)
app$setInputs(sigma2 = 1.8)
app$setInputs(sigma2 = 3.6)
app$setInputs(mu2 = 0.8)
app$setInputs(p2 = 0.85)
app$setInputs(sigma2 = 2.4)
app$setInputs(sigma2 = 1)
app$snapshot()
