app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(x = "1")
app$snapshot()
app$setInputs(disp = "Gaussian Mixture Model")
app$setInputs(alpha = 0.625)
app$snapshot()
app$setInputs(y = "3")
app$snapshot()
app$setInputs(alpha = 0.875)
app$snapshot()
app$setInputs(disp = "K-means clustering")
app$setInputs(x = "2")
app$setInputs(y = "2")
app$snapshot()
app$setInputs(y = "3")
app$setInputs(y = "4")
app$snapshot()
app$setInputs(alpha = 0.375)
app$setInputs(x = "3")
app$snapshot()
app$setInputs(alpha = 0.9)
app$snapshot()
